Initial import of harvest docs from azaroth42
IIIF/discovery pull request #4
Opened 2017-12-11 18:53 UTC by azaroth42

Import revised documentation under harvest and notification.

2017-12-12 15:20 UTC, zimeon requested changes

2017-12-12 15:20 UTC, zimeon commented on source/api/notification/0.1/index.md
> +For the purposes of IIIF discovery, the above decision is firmly in the Notification section of the charter and does not impact the publication of the Activitystreams Collections as resources.
Acitvitystreams -> ActivityStreams

2017-12-12 15:20 UTC, zimeon commented on source/api/harvest/0.1/index.md
> +	"@context": [
In other specs we have 2-space indents in our JSON docs, should we keep with that?

2017-12-12 15:20 UTC, zimeon commented on source/api/harvest/0.1/activities.md
> +#### Split
Is there really any good reason to have split? If the expected behavior is to reharvest both of the new resources then that is the same as delete and 2 creates. 

Saying that the UI might want to group things seems wrong in that one is then saying that the update system is conveying presentation semantics that aren't present in the current state of the resources -- so the grouping would then vanish at some later time?

2017-12-12 15:20 UTC, zimeon commented on source/api/harvest/0.1/activities.md
> +#### Merge
I don't think we should include Merge without a use case, this seems to violate the "As Simple as Possible, and No Simpler" principle

2017-12-12 15:20 UTC, zimeon commented on source/api/notification/0.1/index.md
> +This information is extracted from the Crawling work, as it applies to notifications using the ActivityStreams pattern.
Add link for "Crawling work" and "ActivityStreams" given first mention in the doc?

2017-12-13 16:33 UTC, azaroth42 commented on source/api/harvest/0.1/activities.md
> +#### Merge
How about adding a :warning: warning block to Copy and Merge that they need use cases?  If we take them out completely, they'll get lost.

2017-12-13 16:43 UTC, zimeon commented on source/api/harvest/0.1/activities.md
> +#### Merge
I guess that us a reasonable compromise for an in-process document

2018-01-24 16:34 UTC, azaroth42 commented on source/api/harvest/0.1/activities.md
> +#### Merge
Done.

2018-01-24 16:35 UTC, azaroth42 commented on source/api/harvest/0.1/activities.md
> +#### Split
Agree the UI is not a good consideration.  Added the same warning as for Merge and removed the UI note.

2018-01-24 16:36 UTC, azaroth42 commented on source/api/harvest/0.1/index.md
> +	"@context": [
Yes. Can we do this in a second round?

2018-01-24 16:40 UTC, azaroth42 commented on source/api/notification/0.1/index.md
> +This information is extracted from the Crawling work, as it applies to notifications using the ActivityStreams pattern.
Done

2018-01-24 16:40 UTC, azaroth42 commented on source/api/notification/0.1/index.md
> +For the purposes of IIIF discovery, the above decision is firmly in the Notification section of the charter and does not impact the publication of the Activitystreams Collections as resources.
Done

2018-01-24 16:46 UTC, azaroth42 commented on source/api/harvest/0.1/index.md
> +	"@context": [
Second thoughts ... done :)

2018-01-24 18:15 UTC, zimeon approved these changes

2018-01-24 18:46 UTC, mikeapp approved these changes

2018-01-24 18:47 UTC, merged